version: "3.8"

## FOR TEST AND DEVELOPMENT ONLY, DO NOT USE IN PRODUCTION   ##

name: vidre-dev

services:
  backend:
    container_name: vidre-backend-dev
    image: vidre-backend-dev
    build:
      context: ./
      dockerfile: docker/Dockerfile.dev
    restart: always
    depends_on:
      postgres:
        condition: service_healthy
    expose:
      - 8081
    ports:
      - "8081:8081" # database port (host:container)
    env_file:
      - .env
    volumes:
      - ./:/app
    networks:
      - network-backend

  postgres:
    container_name: postgres-vidre-dev
    image: postgres:15-alpine
    user: postgres
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data # postgres-data: ./postgres-data:
    expose:
      - 5433
    ports:
      - "5433:5433" # database port (host:container)
    env_file:
      - .env
    networks:
      - network-backend
    healthcheck:
      test: [ "CMD", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  network-backend:
volumes:
  postgres-data:
    external: true
    name: postgres-data
